## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
dist: xenial
os:
  - linux
  - osx
julia:
  - 1.2
  - 1.5
  - nightly
notifications:
  email: false
git:
  depth: 99999999

jobs:
  allow_failures:
    - julia: nightly
after_success:
  - julia --project=test/coverage -e 'using Pkg; Pkg.instantiate()'
  - julia --project=test/coverage test/coverage/coverage.jl
