name = "FunctionWranglers"
uuid = "b554fa5d-8411-41ee-8688-d60d0f644aa9"
authors = ["Krisztian Schaffer"]
version = "0.1.1"

[compat]
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
